"""remove_zone_id_from_users

Revision ID: 05ce35661476
Revises: b29f3d3a5790
Create Date: 2026-07-10 08:56:11.620347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ce35661476'
down_revision: Union[str, Sequence[str], None] = 'b29f3d3a5790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_zones'), type_='foreignkey')
        batch_op.drop_column('zone_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_zones'), 'zones', ['zone_id'], ['id'])

    # ### end Alembic commands ###
