"""make_zone_id_not_null_in_citizen_reports

Revision ID: 14d977d5064b
Revises: 25e024d1defe
Create Date: 2026-07-05 13:35:54.378551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d977d5064b'
down_revision: Union[str, Sequence[str], None] = '25e024d1defe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.alter_column('zone_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.alter_column('zone_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
