"""add_status_and_is_grouped_to_citizen_reports

Revision ID: 35e5cbafc755
Revises: 507a4f9c3417
Create Date: 2026-07-04 20:49:07.814005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e5cbafc755'
down_revision: Union[str, Sequence[str], None] = '507a4f9c3417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_grouped', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_citizen_reports_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citizen_reports_status'))
        batch_op.drop_column('is_grouped')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
