"""make_driver_id_nullable_in_route_recommendations

Revision ID: 437042889591
Revises: 05ce35661476
Create Date: 2026-07-10 09:09:12.753182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437042889591'
down_revision: Union[str, Sequence[str], None] = '05ce35661476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_recommendations', schema=None) as batch_op:
        batch_op.alter_column('driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_recommendations', schema=None) as batch_op:
        batch_op.alter_column('driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
