"""add_image_path_to_citizen_reports

Revision ID: 587242967124
Revises: 7ca0c949a3eb
Create Date: 2026-07-09 13:34:04.428706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587242967124'
down_revision: Union[str, Sequence[str], None] = '7ca0c949a3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
