"""add_fleet_model_and_link_to_users

Revision ID: b29f3d3a5790
Revises: 587242967124
Create Date: 2026-07-09 21:13:32.760043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29f3d3a5790'
down_revision: Union[str, Sequence[str], None] = '587242967124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('capacity', sa.String(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleets_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleets_type'), ['type'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fleet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_fleets', 'fleets', ['fleet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_fleets', type_='foreignkey')
        batch_op.drop_column('fleet_id')

    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleets_type'))
        batch_op.drop_index(batch_op.f('ix_fleets_name'))
        batch_op.drop_index(batch_op.f('ix_fleets_id'))
        batch_op.drop_index(batch_op.f('ix_fleets_category'))

    op.drop_table('fleets')
    # ### end Alembic commands ###
