"""merge_admin_and_driver_and_update_route_recommendations

Revision ID: c6b8239019ef
Revises: 35e5cbafc755
Create Date: 2026-07-05 12:17:29.516636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b8239019ef'
down_revision: Union[str, Sequence[str], None] = '35e5cbafc755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers')
    with op.batch_alter_table('route_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.alter_column('route_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_foreign_key('fk_route_recommendations_users', 'users', ['driver_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('zone_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_users_zones', 'zones', ['zone_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_zones', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('zone_id')
        batch_op.drop_column('whatsapp_number')
        batch_op.drop_column('name')

    with op.batch_alter_table('route_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_route_recommendations_users', type_='foreignkey')
        batch_op.alter_column('route_json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('driver_id')

    op.create_table('drivers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('whatsapp_number', sa.VARCHAR(), nullable=True),
    sa.Column('zone_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_whatsapp_number'), ['whatsapp_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_id'), ['id'], unique=False)

    # ### end Alembic commands ###
