"""initial_migration

Revision ID: 0f9ca25c77fb
Revises: 
Create Date: 2026-07-02 09:19:03.668985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9ca25c77fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_recommendations_id'), ['id'], unique=False)

    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('risk_status', sa.Enum('Normal', 'Warning', 'High Priority', name='risk_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_name'), ['name'], unique=False)

    op.create_table('citizen_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('report_content', sa.String(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citizen_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_reports_whatsapp_number'), ['whatsapp_number'], unique=False)

    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.String(), nullable=True),
    sa.Column('fill_percentage', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_data_sensor_type'), ['sensor_type'], unique=False)

    op.create_table('volume_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('predicted_volume', sa.Float(), nullable=True),
    sa.Column('target_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volume_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volume_predictions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volume_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volume_predictions_id'))

    op.drop_table('volume_predictions')
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_data_sensor_type'))
        batch_op.drop_index(batch_op.f('ix_sensor_data_id'))

    op.drop_table('sensor_data')
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citizen_reports_whatsapp_number'))
        batch_op.drop_index(batch_op.f('ix_citizen_reports_id'))

    op.drop_table('citizen_reports')
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_name'))
        batch_op.drop_index(batch_op.f('ix_zones_id'))

    op.drop_table('zones')
    with op.batch_alter_table('route_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_recommendations_id'))

    op.drop_table('route_recommendations')
    # ### end Alembic commands ###
