"""add_tps_fields_to_zones

Revision ID: 1f167cb7ca1a
Revises: 14d977d5064b
Create Date: 2026-07-06 22:20:23.555768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f167cb7ca1a'
down_revision: Union[str, Sequence[str], None] = '14d977d5064b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wilayah', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('kecamatan', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('kelurahan', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('jenis_tps', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('alamat', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_column('alamat')
        batch_op.drop_column('jenis_tps')
        batch_op.drop_column('kelurahan')
        batch_op.drop_column('kecamatan')
        batch_op.drop_column('wilayah')

    # ### end Alembic commands ###
