"""make_zone_id_nullable_in_citizen_reports

Revision ID: 25e024d1defe
Revises: c6b8239019ef
Create Date: 2026-07-05 13:19:00.341071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e024d1defe'
down_revision: Union[str, Sequence[str], None] = 'c6b8239019ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.alter_column('zone_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.alter_column('zone_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
