"""add type to citizen reports

Revision ID: 9cebd0fda733
Revises: a5c92226eda1
Create Date: 2026-07-15 08:45:07.696709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cebd0fda733'
down_revision: Union[str, Sequence[str], None] = 'a5c92226eda1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('waste', 'event', name='report_type_enum'), nullable=False))
        batch_op.create_index(batch_op.f('ix_citizen_reports_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citizen_reports_type'))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
