"""Add historical_waste_data table

Revision ID: a0ff987b38d7
Revises: 437042889591
Create Date: 2026-07-10 12:31:17.541667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ff987b38d7'
down_revision: Union[str, Sequence[str], None] = '437042889591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_waste_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kecamatan', sa.String(), nullable=True),
    sa.Column('tps_id', sa.String(), nullable=True),
    sa.Column('tps_type', sa.String(), nullable=True),
    sa.Column('zone_population', sa.Integer(), nullable=True),
    sa.Column('tps_capacity_kg', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_weekend', sa.Integer(), nullable=True),
    sa.Column('is_holiday', sa.Integer(), nullable=True),
    sa.Column('daily_growth_rate', sa.Float(), nullable=True),
    sa.Column('rainfall_today', sa.Float(), nullable=True),
    sa.Column('event_urgency_score', sa.Float(), nullable=True),
    sa.Column('current_fill_percentage', sa.Float(), nullable=True),
    sa.Column('target_fill_percentage', sa.Float(), nullable=True),
    sa.Column('timestamp_prediction', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_waste_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_waste_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_waste_data_tps_id'), ['tps_id'], unique=False)

    with op.batch_alter_table('volume_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predicted_volume_percentage', sa.Float(), nullable=True))
        batch_op.drop_column('predicted_volume')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volume_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predicted_volume', sa.FLOAT(), nullable=True))
        batch_op.drop_column('predicted_volume_percentage')

    with op.batch_alter_table('historical_waste_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_waste_data_tps_id'))
        batch_op.drop_index(batch_op.f('ix_historical_waste_data_id'))

    op.drop_table('historical_waste_data')
    # ### end Alembic commands ###
