"""add_indexes_to_zones_and_sensor_data

Revision ID: a1d8b2be6ce8
Revises: 40d866b010ce
Create Date: 2026-07-08 17:29:20.088994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d8b2be6ce8'
down_revision: Union[str, Sequence[str], None] = '40d866b010ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_data_zone_id'), ['zone_id'], unique=False)

    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zones_kecamatan'), ['kecamatan'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_kelurahan'), ['kelurahan'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_risk_status'), ['risk_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_wilayah'), ['wilayah'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_wilayah'))
        batch_op.drop_index(batch_op.f('ix_zones_risk_status'))
        batch_op.drop_index(batch_op.f('ix_zones_kelurahan'))
        batch_op.drop_index(batch_op.f('ix_zones_kecamatan'))

    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_data_zone_id'))

    # ### end Alembic commands ###
