"""fresh_initial_schema

Revision ID: a5c92226eda1
Revises: 
Create Date: 2026-07-14 14:06:08.474640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c92226eda1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('capacity', sa.String(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleets_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleets_type'), ['type'], unique=False)

    op.create_table('historical_waste_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kecamatan', sa.String(), nullable=True),
    sa.Column('tps_id', sa.Integer(), nullable=True),
    sa.Column('tps_type', sa.String(), nullable=True),
    sa.Column('zone_population', sa.Integer(), nullable=True),
    sa.Column('tps_capacity_kg', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_weekend', sa.Integer(), nullable=True),
    sa.Column('is_holiday', sa.Integer(), nullable=True),
    sa.Column('daily_growth_rate', sa.Float(), nullable=True),
    sa.Column('rainfall_today', sa.Float(), nullable=True),
    sa.Column('event_urgency_score', sa.Float(), nullable=True),
    sa.Column('current_fill_percentage', sa.Float(), nullable=True),
    sa.Column('timestamp_prediction', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_waste_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_waste_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_waste_data_tps_id'), ['tps_id'], unique=False)

    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('wilayah', sa.String(), nullable=True),
    sa.Column('kecamatan', sa.String(), nullable=True),
    sa.Column('kelurahan', sa.String(), nullable=True),
    sa.Column('jenis_tps', sa.String(), nullable=True),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('risk_status', sa.Enum('Normal', 'Warning', 'High Priority', name='risk_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_kecamatan'), ['kecamatan'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_kelurahan'), ['kelurahan'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_risk_status'), ['risk_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_wilayah'), ['wilayah'], unique=False)

    op.create_table('citizen_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('report_content', sa.String(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_grouped', sa.Boolean(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citizen_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_reports_whatsapp_number'), ['whatsapp_number'], unique=False)

    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.String(), nullable=True),
    sa.Column('fill_percentage', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_data_sensor_type'), ['sensor_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_data_zone_id'), ['zone_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('fleet_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('coverage_area', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('volume_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_batch_id', sa.String(length=30), nullable=True),
    sa.Column('kecamatan', sa.String(), nullable=False),
    sa.Column('tps_id', sa.Integer(), nullable=False),
    sa.Column('predicted_volume_percentage', sa.Float(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('prediction_status', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kecamatan'], ['zones.kecamatan'], ),
    sa.ForeignKeyConstraint(['tps_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volume_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volume_predictions_forecast_batch_id'), ['forecast_batch_id'], unique=False)

    op.create_table('route_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_batch_id', sa.String(length=30), nullable=True),
    sa.Column('coverage_area', sa.String(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('total_stops', sa.Integer(), nullable=True),
    sa.Column('route_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_recommendations_coverage_area'), ['coverage_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_recommendations_forecast_batch_id'), ['forecast_batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_recommendations_forecast_batch_id'))
        batch_op.drop_index(batch_op.f('ix_route_recommendations_coverage_area'))

    op.drop_table('route_recommendations')
    with op.batch_alter_table('volume_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volume_predictions_forecast_batch_id'))

    op.drop_table('volume_predictions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_data_zone_id'))
        batch_op.drop_index(batch_op.f('ix_sensor_data_sensor_type'))
        batch_op.drop_index(batch_op.f('ix_sensor_data_id'))

    op.drop_table('sensor_data')
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citizen_reports_whatsapp_number'))
        batch_op.drop_index(batch_op.f('ix_citizen_reports_status'))
        batch_op.drop_index(batch_op.f('ix_citizen_reports_id'))

    op.drop_table('citizen_reports')
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_wilayah'))
        batch_op.drop_index(batch_op.f('ix_zones_risk_status'))
        batch_op.drop_index(batch_op.f('ix_zones_name'))
        batch_op.drop_index(batch_op.f('ix_zones_kelurahan'))
        batch_op.drop_index(batch_op.f('ix_zones_kecamatan'))
        batch_op.drop_index(batch_op.f('ix_zones_id'))

    op.drop_table('zones')
    with op.batch_alter_table('historical_waste_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_waste_data_tps_id'))
        batch_op.drop_index(batch_op.f('ix_historical_waste_data_id'))

    op.drop_table('historical_waste_data')
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleets_type'))
        batch_op.drop_index(batch_op.f('ix_fleets_name'))
        batch_op.drop_index(batch_op.f('ix_fleets_id'))
        batch_op.drop_index(batch_op.f('ix_fleets_category'))

    op.drop_table('fleets')
    # ### end Alembic commands ###
