"""add_forecast_batch_id_to_route_recommendations

Revision ID: d5243389e5d4
Revises: df9180bdb858
Create Date: 2026-07-14 06:21:50.869019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5243389e5d4'
down_revision: Union[str, Sequence[str], None] = 'df9180bdb858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_waste_data', schema=None) as batch_op:
        batch_op.alter_column('tps_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('target_fill_percentage')

    with op.batch_alter_table('route_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forecast_batch_id', sa.String(length=30), nullable=True))
        batch_op.alter_column('route_json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_route_recommendations_id'))
        batch_op.create_index(batch_op.f('ix_route_recommendations_forecast_batch_id'), ['forecast_batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_recommendations_forecast_batch_id'))
        batch_op.create_index(batch_op.f('ix_route_recommendations_id'), ['id'], unique=False)
        batch_op.alter_column('route_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('forecast_batch_id')

    with op.batch_alter_table('historical_waste_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_fill_percentage', sa.FLOAT(), nullable=True))
        batch_op.alter_column('tps_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
